[package]
name = "websocket-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.23.0"
futures-util = "0.3"
reqwest = { version = "0.12.4", features = ["json"] }
